#!/usr/bin/env bash

MODULES_PATH=${VPM_MODULES_PATH:-"$HOME/.vagrant_modules"}
MODULES_PREFIX="$MODULES_PATH/$(basename $(pwd))"

if test $1 = 'init'; then
  mkdir -p $MODULES_PREFIX
  ln -s $MODULES_PREFIX/node_modules node_modules
  echo "Created link node_modules -> $MODULES_PREFIX/node_modules"
fi
